<?php
namespace frontend\widgets;


use backend\models\GoodsCategory;
use yii\base\Widget;

class CategoryWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function run()
    {
        //实例化redis
        $redis=new \Redis();
        //连接redis
        $redis->connect('127.0.0.1');
        //操作redis
        $category_html = $redis->get('categories');

        if($category_html == null){
            $categories=GoodsCategory::findAll(['parent_id'=>0]);
            $category_html=$this->renderFile('@app/widgets/view/category.php',['categories'=>$categories]);
             $redis->set('categories',$category_html,24*3600);
        }

        return $category_html;
    }

}